// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7InwhiDdar8kVpudBBZ0U2C-SYFyiNrY',
    appId: '1:884254093205:web:2704935aba0d40edce109c',
    messagingSenderId: '884254093205',
    projectId: 'sorto-dares',
    authDomain: 'sorto-dares.firebaseapp.com',
    storageBucket: 'sorto-dares.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJn-QqzfTuvRxSuLGQxBeoaVahV-7DeY',
    appId: '1:884254093205:android:47d62cdf66d50fbace109c',
    messagingSenderId: '884254093205',
    projectId: 'sorto-dares',
    storageBucket: 'sorto-dares.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkM8CpDWjGDXQ7SMlkiVxs6UerB6pr9xY',
    appId: '1:884254093205:ios:ca30d6d27180f9b8ce109c',
    messagingSenderId: '884254093205',
    projectId: 'sorto-dares',
    storageBucket: 'sorto-dares.firebasestorage.app',
    androidClientId: '884254093205-p1j9r35j37n9n3uga44kj1socvh442je.apps.googleusercontent.com',
    iosClientId: '884254093205-tvnlarva4etqjoahthnmrj1fo3psv04i.apps.googleusercontent.com',
    iosBundleId: 'me.ritom.sorto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkM8CpDWjGDXQ7SMlkiVxs6UerB6pr9xY',
    appId: '1:884254093205:ios:ca30d6d27180f9b8ce109c',
    messagingSenderId: '884254093205',
    projectId: 'sorto-dares',
    storageBucket: 'sorto-dares.firebasestorage.app',
    androidClientId: '884254093205-p1j9r35j37n9n3uga44kj1socvh442je.apps.googleusercontent.com',
    iosClientId: '884254093205-tvnlarva4etqjoahthnmrj1fo3psv04i.apps.googleusercontent.com',
    iosBundleId: 'me.ritom.sorto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7InwhiDdar8kVpudBBZ0U2C-SYFyiNrY',
    appId: '1:884254093205:web:ee8451f7d914cba1ce109c',
    messagingSenderId: '884254093205',
    projectId: 'sorto-dares',
    authDomain: 'sorto-dares.firebaseapp.com',
    storageBucket: 'sorto-dares.firebasestorage.app',
  );

}